library(readr)
temp <- read_csv("temp.csv")
View(temp)
hist(temp$actual_mean_temp)
hist(temp$actual_mean_temp,main = "Temperature changes", xlab= "Temperature", ylab= "Number of days")
hist(temp$actual_max_temp)
hist(temp$actual_max_temp, main= "Temperature changes", xlab= "Maximum temperature", ylab= "Number of days")
barplot(table(temp$month))
barplot(table(temp$month), main = "Seasonal changes", ylab= "Temperature", xlab= "Months")
hist(temp$record_min_temp)
hist(temp$record_min_temp, main = "Temperature records", xlab= "Minimum temperature record", ylab= "Frequency")
