library(readr)
temp <- read_csv("temp.csv")
View(temp)
mean(temp$actual_min_temp)
median(temp$actual_min_temp)
var(temp$actual_min_temp)
sd(temp$actual_min_temp)
mean(temp$actual_max_temp)
median(temp$actual_max_temp)
var(temp$actual_max_temp)
sd(temp$actual_max_temp)
